### ISSUE TITLE
resnet shape-adaptor

### ISSUE THREAD

**Issue by freeman-1995** [lorenmt/shape-adaptor#4]
hi~ @lorenmt  

when I use shape-adaptor in resnet50, I find you insert each shape-adaptor into the end of bottlenet, add a lot of extra 1x1 convolution operations to resnet, I think the a part of performace gain is coming from it. Is that True?

![pic](https://user-images.githubusercontent.com/16744729/93728644-5e8ac980-fbf3-11ea-9060-00d8dce2f31b.png)

**Comment by lorenmt** [comment]
Shape adaptors in ResNet are attached to the original residual connection. At the first layer of each block, the channel number changes, so we require 1x1 convolution to make channel number consistent in order to perform element-wise addition (this is in the original design). So to keep consistent, we apply a 1x1 conv layer to all shape adaptors attached in the network.

If you visualize the network structure, you can observe that there are not many additional 1x1 layers inserted (maybe 1 or 2 extra, depending on how many shape adaptors inserted). That is mainly because most of the time, shape adaptors are luckily inserted at the first layer of each block, so we could just directly apply the 1x1 conv layer defined in the original network.

Again, you can modify the design, to remove all 1x1 conv layers if not having channel consistency issue. I am pretty confident it will still increase the network performance by a large margin.

In the original MobileNet design, the residual connection is only applied when stride = 2 (when shape changes). Since shape adaptor requires no stride in the network, thus all shape adaptors are applied based on a VGG style of connection, and thus no additional parameters introduced.

It's unfair to say the performance is based on additional parameters, as there are either very few or no extra parameters introduced using shape adaptors.

**Comment by freeman-1995** [comment]
ok,  I also curious about the design of shape-adaptor module, why it has two branch?

**Comment by lorenmt** [comment]
We need at least wo branches to define the search space, i.e. one branch is the maximal reshaping factor, one is the minimal reshaping factor.

**Comment by freeman-1995** [comment]
Maybe I just only use one branch,  alpha can also be differentiable with a limit (r_min, r_max), so can it bring better performance if using two branches?

**Comment by lorenmt** [comment]
I don’t understand. Shape adaptor must be designed with at least two branches.
